name: Build images

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:  # from https://deb.theforeman.org/pool/
        - '1.21'
        - '1.22'
        - '1.23'
        - '1.24'
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
    steps:
    - uses: actions/checkout@v2
    - name: Build hammer ${{ matrix.version }}
      run: docker build . --build-arg FOREMAN_VERSION=${{ matrix.version }} --tag quay.io/foreman/hammer:${{ matrix.version }}
    - name: Publish hammer ${{ matrix.version }}
      run: |
        - docker login quay.io -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}"
        - docker push quay.io/foreman/hammer:${{ matrix.version }}
